### ISSUE TITLE
Issue in linking back to the homepage

### ISSUE THREAD

**Issue by romangraef** [Hallo89/hallo89.net#1]
https://hallo89.net/webgl/triangles links back to the main page in the top right corner, but redirects to /index.html which is not mapped and results in a 404 on https://hallo89.net/index.html

**Comment by Hallo89** [comment]
Fixed in https://github.com/Hallo89/hallo89.net/commit/cb8ca4514e63109442962d52230b6ff7727501f7 and just pushed!
